name: Build
on:
  push:
    branches:
      - "master"
  pull_request:
    branches:
      - "*"

jobs:
  validation:
    name: Validate Gradle Wrapper
    runs-on: ubuntu-latest
    steps:
      - name: Checkout latest code
        uses: actions/checkout@v2
      - name: Validate Gradle Wrapper
        uses: gradle/wrapper-validation-action@v1
  gradle:
    name: Build Gradle Tasks
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    if: ${{ !contains(github.event.head_commit.message, 'ci skip') }}
    steps:
      - uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Checkout Repo
        uses: actions/checkout@v2
      - name: Cache Gradle Caches
        uses: actions/cache@v1
        with:
          path: ~/.gradle/caches/
          key: cache-gradle-cache
      - name: Cache Gradle Wrapper
        uses: actions/cache@v1
        with:
          path: ~/.gradle/wrapper/
          key: cache-gradle-wrapper
      - name: Run Gradle tasks
        run: ./gradlew build --continue
      - name: Stop Gradle
        run: ./gradlew --stop
